blog/urls.py
from django.urls import path

from blog.views import PostDetailView, PostListView

urlpatterns = [
    path('post/<slug:slug>', PostDetailView.as_view(), name='post_detail'),
    path('posts/', PostListView.as_view(), name='post_list'),
]

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('', include('anime.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

anime/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from .choices import STATUS_CHOICES, QUALITY_CHOICES, TYPE_CHOICES

User = get_user_model()


class Studio(models.Model):
    """
    Модель для студии
    """
    name = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Студия'
        verbose_name_plural = 'Студии'

    def __str__(self):
        return self.name


class Genre(models.Model):
    """
    Модель для жанра
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    Модель для категории
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Anime(models.Model):
    """
    Модель для аниме
    """
    title = models.CharField(max_length=200, verbose_name='Название')
    japan_title = models.CharField(max_length=200, verbose_name='Название на японском')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.CharField(max_length=500, verbose_name='Описание')
    type = models.CharField(max_length=100, verbose_name='Тип показа', choices=TYPE_CHOICES)
    studio = models.ForeignKey(Studio, on_delete=models.CASCADE, verbose_name='Студия', related_name='animes')
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата окончания', null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='Статус')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры', related_name='animes')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', related_name='animes')
    expected_episode_count = models.IntegerField(default=0, verbose_name='Ожидаемое кол-во эпизодов')
    duration = models.IntegerField(verbose_name='Длительность эпизода')
    views = models.IntegerField(verbose_name='Просмотры', default=0)
    quality = models.CharField(max_length=10, choices=QUALITY_CHOICES, verbose_name='Качество')
    poster = models.ImageField(upload_to='posters/', verbose_name='Постер')
    poster_for_feature = models.ImageField(upload_to='feature_posters/', verbose_name='Постер для фичинга', blank=True,
                                           null=True)
    is_featured = models.BooleanField(default=False, blank=True, verbose_name='Фичеринг(отображение на главной)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Аниме'
        verbose_name_plural = 'Аниме'

    def increment_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title


class Vote(models.Model):
    """
    Модель для голоса
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='votes')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, verbose_name='Аниме', related_name='votes')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Рейтинг')

    class Meta:
        verbose_name = 'Голос'
        verbose_name_plural = 'Голоса'

    def __str__(self):
        return f'{self.author.username} {self.anime} - {self.rating}'


class FollowingAnime(models.Model):
    """
    Модель для избранного аниме
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь',
                             related_name='folowing_animes')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, verbose_name='Аниме')

    class Meta:
        verbose_name = 'Любимое аниме'
        verbose_name_plural = 'Любимые аниме'

    def __str__(self):
        return f'{self.user.username} - {self.anime}'


class Episode(models.Model):
    """
    Модель для эпизодо
    """
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(verbose_name='Слаг')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name='episodes', verbose_name='Аниме')
    video = models.FileField(upload_to='episodes/', verbose_name='Эпизод(видео)')
    poster = models.ImageField(upload_to='episode_posters/', verbose_name='Постер')

    class Meta:
        verbose_name = 'Эпизод'
        verbose_name_plural = 'Эпизоды'

    def __str__(self):
        return f'{self.anime} - {self.title}'


class AnimeReview(models.Model):
    """
    Модель для комментария к аниме
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='anime_reviews', verbose_name='Автор')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name='reviews', verbose_name='Аниме')
    text = models.CharField(max_length=300, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Комментарий к аниме'
        verbose_name_plural = 'Комментарии к аниме'

    def __str__(self):
        return f'{self.author.username} - {self.anime}'


class EpisodeReview(models.Model):
    """
       Модель для комментария к эпизоду
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='episode_reviews', verbose_name='Автор')
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE, related_name='reviews', verbose_name='Эпизод')
    text = models.CharField(max_length=300, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Комментарий к эпизоду'
        verbose_name_plural = 'Комментарии к эпизодам'

    def __str__(self):
        return f'{self.author.username} - {self.episode}'

base/templates/base.html
{% load static %}
{% load base_tags %}

<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Anime | Template</title>

    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>

<div id="preloder">
    <div class="loader"></div>
</div>

{% header %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}


<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form" method="get" action="{% url 'search_result' %}">
            <input type="text" id="search-input" placeholder="Поиск аниме..." name="p">
        </form>
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

base/templates/footer.html
{% load static %}

<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span style="top: 5px;" class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="{% url 'anime_index' %}">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="{% url 'anime_index' %}">Главная</a></li>
                        <li><a href="{% url 'anime_list' slug='all' %}">Категории</a></li>
                        <li><a href="{% url 'post_list' %}">Блог</a></li>
                        <li><a href="{%url 'contact' %}">Контакты</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Копирайт &copy;<script>document.write(new Date().getFullYear());</script>
                    Все права защищены | Этот сайт сделан <a href="https://gitlab.com/HomeSani"
                                                             target="_blank">HomeSani</a> c <i class="fa fa-heart"
                                                                                               aria-hidden="true"></i>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

            </div>
        </div>
    </div>
</footer>

base/templates/header.html
{% load static %}

<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'anime_index' %}">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="{% url 'anime_index' %}">Главная</a></li>
                            <li><a href="{% url 'anime_list' slug='all' %}">Категории <span
                                    class="arrow_carrot-down"></span></a>
                                <ul class="dropdown">
                                    {% for category in categories %}
                                        <li><a href="{% url 'anime_list' slug=category.slug %}">{{ category.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li><a href="{% url 'post_list' %}">Блог</a></li>
                            <li><a href="{%url 'contact' %}">Контакты</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    {% if context.request.user.is_authenticated %}
                        <a href="{% url 'account_detail' %}?active_tab=profile"><img
                                style="width: 30px; height: 30px; border-radius: 100%; margin-right: 5px;"
                                src="{{ MEDIA_URL }}{{ context.request.user.avatar.url }}" alt="">
                            <span>{{ context.request.user.username }}</span></a>
                    {% else %}
                        <a href="{% url 'singin' %}">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>